language: node_js
node_js:
  - "stable"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
  - "iojs"
before_install:
  - sudo npm install -g typescript
  - sudo npm install -g jasmine
  
